
name = "Iot Link Server"

version = "1.0.0"

[influx]
host = "http://192.168.10.101:8086"
database = "sensordata"

[db]
host = "192.168.1.252"
database = "iot"
port = 5432
user = "postgres"
password = "postgres"

[web]
listen = ":80"

[down-link]
fetch-size = 10
# idle if no downLink data (Millisecond)
idle-time = 5000
#log-enable = false
